### ISSUE TITLE
AttributeError: 'str' object has no attribute 'keys' during execution

### ISSUE THREAD

**Issue by ilisparrow** [yihui-he/epipolar-transformers#4]
Hello, 
I really liked your work and would like to test the network !

Thank you for making it available.
I had a small problem which I think might be a bug, everything loads fine at the beginning, then it crashes saying that some string, isn't a dictionnary.
Here is an output from my terminal.

I have one more question, where are the test files stored ? If I want to imput my own picture, where do I put it, and where do I tell you algorithm the path to it ?

Thank you very much in advance for your answers !

Best regards,

````
python main.py --cfg configs/epipolar/keypoint_h36m_resnet152_384_pretrained_8gpu.yaml DOTRAIN False WEIGHTS outs/pose_resnet_4.5_pixels_human36m.pth
2020-06-01 01:04:41,493 kp INFO: Namespace(cfg='configs/epipolar/keypoint_h36m_resnet152_384_pretrained_8gpu.yaml', opts=['DOTRAIN', 'False', 'WEIGHTS', 'outs/pose_resnet_4.5_pixels_human36m.pth'])
2020-06-01 01:04:41,493 kp INFO: Loaded configuration file configs/epipolar/keypoint_h36m_resnet152_384_pretrained_8gpu.yaml
2020-06-01 01:04:41,493 kp INFO: 
DATASETS:
    TRAIN: ('multiview_h36m_train',)
    #TRAIN: ('h36m_val',)
    TEST: ('multiview_h36m_val', )
    TASK: multiview_keypoint
    DATA_FORMAT: jpg
    IMAGE_SIZE: (384, 384)
    IMAGE_RESIZE: 1. #3.90625 #1000. / 256 
    PREDICT_RESIZE: 1. 
    H36M:
        TRAIN_SAMPLE: 0
        MAPPING: False
DATALOADER:
    NUM_WORKERS: 20
BACKBONE:
    ENABLED: True
    BODY: epipolarposeR-152
    PRETRAINED: True
    PRETRAINED_WEIGHTS: datasets/pose_resnet_4.5_pixels_human36m.pth
    DOWNSAMPLE: 4
    SYNC_BN: True
SOLVER:
    OPTIMIZER: adam
    BASE_LR: 0.001
    STEPS: (2, 3)
    MAX_EPOCHS: 4
    IMS_PER_BATCH: 32
    CHECKPOINT_PERIOD: 1
EPIPOLAR:
    TOPK: 1
    MERGE: late
    SHARE_WEIGHTS: True 
    ATTENTION: avg
    PARAMETERIZED: ('z',)
    PRETRAINED: False
    ZRESIDUAL: True
    SAMPLESIZE: 64
    USE_CORRECT_NORMALIZE: True
TEST:
    IMS_PER_BATCH: 1
KEYPOINT:
    HEATMAP_SIZE: (96, 96)
    SIGMA: 12.
    NUM_PTS: 17
    TRIANGULATION: epipolar
    CONF_THRES: .85
    RANSAC_THRES: 35
    LOSS: joint
    LOSS_PER_JOINT: False
VIS:
    MULTIVIEW: True
OUTPUT_DIR: outs/epipolar/dgx/keypoint_h36m_resnet152_384_8gpu
EVAL_FREQ: 1

2020-06-01 01:04:41,493 kp INFO: Running with config:
BACKBONE:
  BN_MOMENTUM: 0.1
  BODY: epipolarposeR-152
  DOWNSAMPLE: 4
  ENABLED: True
  PRETRAINED: True
  PRETRAINED_WEIGHTS: datasets/pose_resnet_4.5_pixels_human36m.pth
  SYNC_BN: True
DATALOADER:
  BENCHMARK: False
  NUM_WORKERS: 20
  PIN_MEMORY: True
DATASETS:
  CAMERAS: ()
  COMPLETENESS: 1.0
  CROP_AFTER_RESIZE: False
  CROP_SIZE: (512, 320)
  DATA_FORMAT: jpg
  H36M:
    FILTER_DAMAGE: True
    MAPPING: False
    REAL3D: True
    TEST_SAMPLE: 64
    TRAIN_SAMPLE: 0
  IMAGE_RESIZE: 1.0
  IMAGE_SIZE: (384, 384)
  INCLUDE_GREY_IMGS: True
  PREDICT_RESIZE: 1.0
  ROT_FACTOR: 0
  SCALE_FACTOR: 0.0
  TASK: multiview_keypoint
  TEST: ('multiview_h36m_val',)
  TRAIN: ('multiview_h36m_train',)
  WRIST_COORD: False
DEVICE: cuda
DOTEST: True
DOTRAIN: False
EPIPOLAR:
  ATTENTION: avg
  BOTTLENECK: 1
  FIND_CORR: feature
  MERGE: late
  MULTITEST: False
  OTHER_GRAD: ('other1', 'other2')
  OTHER_ONLY: False
  PARAMETERIZED: ('z',)
  POOLING: False
  PRETRAINED: False
  PRIOR: False
  PRIORMUL: False
  REPROJECT_LOSS_WEIGHT: 0.0
  SAMPLESIZE: 64
  SHARE_WEIGHTS: True
  SIMILARITY: dot
  SIM_LOSS_WEIGHT: 0.0
  SOFTMAXBETA: True
  SOFTMAXSCALE: 0.125
  SOFTMAX_ENABLED: True
  TOPK: 1
  TOPK_RANGE: (1, 2)
  USE_CORRECT_NORMALIZE: True
  VIS: False
  WARPEDHEATMAP: False
  ZRESIDUAL: True
EVAL_FREQ: 1
FOLDER_NAME: outs/epipolar/dgx/keypoint_h36m_resnet152_384_8gpu/01-Jun-at-01-04-41
KEYPOINT:
  CONF_THRES: 0.85
  ENABLED: False
  HEATMAP_SIZE: (96, 96)
  LOSS: joint
  LOSS_PER_JOINT: False
  NFEATS: 256
  NUM_CAM: 0
  NUM_PTS: 17
  RANSAC_THRES: 35
  ROOTIDX: 0
  SIGMA: 12.0
  TRIANGULATION: epipolar
LIFTING:
  AVELOSS_KP: False
  CROP_SIZE: 256
  ENABLED: False
  FLIP_ON: False
  IMAGE_SIZE: 320
  MULTIVIEW_MEDIUM: True
  MULTIVIEW_UPPERBOUND: False
  VIEW_ON: False
LOG_FREQ: 100
OUTPUT_DIR: outs/epipolar/dgx/keypoint_h36m_resnet152_384_8gpu
PICT_STRUCT:
  DEBUG: False
  FIRST_NBINS: 16
  GRID_SIZE: 2000
  LIMB_LENGTH_TOLERANCE: 150
  PAIRWISE_FILE: datasets/h36m/pairwise.pkl
  RECUR_DEPTH: 10
  RECUR_NBINS: 2
  SHOW_CROPIMG: False
  SHOW_HEATIMG: False
  SHOW_ORIIMG: False
  TEST_PAIRWISE: False
SEED: 0
SOLVER:
  BASE_LR: 0.001
  BATCH_MUL: 1
  CHECKPOINT_PERIOD: 1
  FINETUNE: False
  FINETUNE_FREEZE: True
  GAMMA: 0.1
  IMS_PER_BATCH: 32
  MAX_EPOCHS: 4
  MOMENTUM: 0.9
  OPTIMIZER: adam
  SCHEDULER: multistep
  STEPS: (2, 3)
  WEIGHT_DECAY: 0.0
TENSORBOARD:
  COMMENT: 
  USE: True
TEST:
  EPEMEAN_MAX_DIST: 150
  IMS_PER_BATCH: 1
  MAX_TH: 20
  PCK: True
  RECOMPUTE_BN: False
  THRESHOLDS: (1, 2, 5, 10, 20, 30, 40, 50, 60, 80, 100)
  TRAIN_BN: False
VIS:
  AUC: False
  CURSOR: False
  DOVIS: True
  EPIPOLAR_LINE: False
  FLOPS: False
  H36M: False
  MULTIVIEW: True
  MULTIVIEWH36M: False
  POINTCLOUD: False
  SAVE_PRED: False
  SAVE_PRED_FREQ: 100
  SAVE_PRED_LIMIT: -1
  SAVE_PRED_NAME: predictions.pth
  VIDEO: False
  VIDEO_GT: False
WEIGHTS: outs/pose_resnet_4.5_pixels_human36m.pth
WEIGHTS_ALLOW_DIFF_PREFIX: False
WEIGHTS_LOAD_OPT: True
WEIGHTS_PREFIX: module.
WEIGHTS_PREFIX_REPLACE: 
2020-06-01 01:04:41,847 resnet INFO: => loading pretrained model from web
2020-06-01 01:04:41,847 resnet INFO: => init deconv weights from normal distribution
2020-06-01 01:04:41,848 resnet INFO: => init 0.weight as normal(0, 0.001)
2020-06-01 01:04:41,848 resnet INFO: => init 0.bias as 0
2020-06-01 01:04:41,894 resnet INFO: => init 1.weight as 1
2020-06-01 01:04:41,894 resnet INFO: => init 1.bias as 0
2020-06-01 01:04:41,894 resnet INFO: => init 3.weight as normal(0, 0.001)
2020-06-01 01:04:41,894 resnet INFO: => init 3.bias as 0
2020-06-01 01:04:41,900 resnet INFO: => init 4.weight as 1
2020-06-01 01:04:41,900 resnet INFO: => init 4.bias as 0
2020-06-01 01:04:41,900 resnet INFO: => init 6.weight as normal(0, 0.001)
2020-06-01 01:04:41,900 resnet INFO: => init 6.bias as 0
2020-06-01 01:04:41,906 resnet INFO: => init 7.weight as 1
2020-06-01 01:04:41,906 resnet INFO: => init 7.bias as 0
2020-06-01 01:04:41,906 resnet INFO: => init final conv weights from normal distribution
2020-06-01 01:04:41,906 resnet INFO: => init 8.weight as normal(0, 0.001)
2020-06-01 01:04:41,906 resnet INFO: => init 8.bias as 0
Traceback (most recent call last):
  File "main.py", line 75, in <module>
    main()
  File "main.py", line 68, in main
    test(cfg)
  File "/home/USER/Bureau/posEstimation/epipolar-transformers/engine/tester.py", line 31, in test
    model = Modelbuilder(cfg)
  File "/home/USER/Bureau/posEstimation/epipolar-transformers/modeling/model.py", line 34, in __init__
    self.reference = registry.BACKBONES[cfg.BACKBONE.BODY](cfg)
  File "/home/USER/Bureau/posEstimation/epipolar-transformers/modeling/backbones/resnet.py", line 515, in get_pose_net
    model.init_weights(cfg.BACKBONE.PRETRAINED_WEIGHTS)
  File "/home/USER/Bureau/posEstimation/epipolar-transformers/modeling/backbones/resnet.py", line 471, in init_weights
    load_state_dict(self, pretrained_state_dict, strict=False, ignored_layers=['final_layer.bias', 'final_layer.weight'], prefix=cfg.WEIGHTS_PREFIX, prefix_replace=cfg.WEIGHTS_PREFIX_REPLACE)
  File "/home/USER/Bureau/posEstimation/epipolar-transformers/utils/model_serialization.py", line 80, in load_state_dict
    if 'model' in loaded_state_dict.keys():
AttributeError: 'str' object has no attribute 'keys'

```

**Comment by yihui-he** [comment]
Could you confirm `datasets/pose_resnet_4.5_pixels_human36m.pth` exist? I don't have a machine to debug right now. Will get back to you later

**Comment by yihui-he** [comment]
For testing, you need to create a customized dataset and modify `DATASETS.TEST` in the cfg. After running the test, a `output.pkl` will be stored for visualization. Have a look at the visualization ipython notebook https://github.com/yihui-he/epipolar-transformers#epipolar-transformers-visualization
